### ISSUE TITLE
Attribute parsing does not handle escaped backslashes correctly

### ISSUE THREAD

**Issue by oliverhanappi** [jrfonseca/xdot.py#19] opened 2015-05-07 17:29 UTC
I am trying to open the following DOT-file with xdot:

```
digraph g {
    n0 [label = "\\\"test\\\""];
}
```

xdot shows an error: `8:85:unexpected char '\'`

The file is however valid code and can be parsed and rendered with graphviz:

![test](https://cloud.githubusercontent.com/assets/401938/7521593/4f4b6ba2-f4ef-11e4-80b8-bc7921f9fc8d.png)

**Comment by jrfonseca** [comment] 2015-05-08 00:41
This is a bug in dot's xdot backend.  xdot files are supposed to be valid dot files, but dot is not preserving the double backslash characters properly when writing the xdot:

    $ dot -Txdot quotes.dot 
    digraph g {
    	graph [_draw_="c 9 -#fffffe00 C 7 -#ffffff P 4 0 0 0 36 71.49 36 71.49 0 ",
    		bb="0,0,71.494,36",
    		xdotversion=1.7
    	];
    	node [label="\N"];
    	n0	 [_draw_="c 7 -#000000 e 35.75 18 36 18 ",
    		_ldraw_="F 14 11 -Times-Roman c 7 -#000000 T 35.75 14.3 0 39 8 -\\"test\\" ",
    		height=0.5,
    		label="\\\"test\\\"",
    		pos="35.747,18",
    		width=0.99297];
    }

Dot itself can't parse its own xdot.

And the exact same thing happens with HTML labels:

    $ cat escapes.dot 
    digraph {
        c [label = "\\\""];
        html [label = <\">];
    }
    $ xdot.py ^C
    $ dot -Txdot escapes.dot | dot -Tpng > /dev/null
    Error: <stdin>: syntax error in line 8 near '\'

So there's no workaround.

There's nothing I can do about this on xdot.py.  In short, this must be fixed on dot's xdot backend itself.

**Comment by jrfonseca** [comment] 2015-05-08 01:09
Could you file a bug in http://www.graphviz.org/content/graphviz-issue-tracker and refer this?

I quickly inspected graphviz source code to see a fix was trivial but I couldn't find exactly what portion of the code is responsible for escaping xdot output..

**Comment by oliverhanappi** [comment] 2015-05-26 17:38
I filed the bug in the graphviz bug tracker: http://www.graphviz.org/mantisbt/view.php?id=2547

**Comment by jrfonseca** [comment] 2015-06-09 22:01
Thanks.

**Comment by jrfonseca** [comment] 2017-12-22 18:46
It looks the issue is now being tracked in Gitlab: https://gitlab.com/graphviz/graphviz/issues/165

**Comment by n00b42** [comment] 2021-03-29 13:37
FYI: The referenced Graphviz issue was closed/resolved.

**Comment by jrfonseca** [comment] 2021-03-31 09:28
Excellent!  Thanks for letting me know @n00b42 

It looks like graphviz on Ubuntu 20.04 still doesn't have the fix, so I can't verify yet.  But I'll mark this as resolved nevertheless.

**Closed by jrfonseca** 2021-03-31 09:28 UTC
Labels: thirdparty
