### ISSUE TITLE
Unknown xdot opcode '>' with new graphviz version

### ISSUE THREAD

**Issue by bredelings** [jrfonseca/xdot.py#120] opened 2023-08-08 17:26 UTC
Hi,

I'm trying out the new 8.05 version of graphviz, which is being packaged for Debian.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012864

With the new version of `dot`, xdot.py now yields the error

> error: unknown xdot opcode '>'

but it worked fine with the previous version of graphviz (2.42).

The `dot` program runs fine, and produces good output in either svg (attached) or xdot (attached) format.  So it looks like xdot.py is having trouble parsing the output of `dot -Txdot`.

![factor-13](https://github.com/jrfonseca/xdot.py/assets/140268/e54bac45-35c5-4463-8b0c-afb822440f67)

[factor-13.dot.txt](https://github.com/jrfonseca/xdot.py/files/12294233/factor-13.dot.txt)
[factor-13.xdot.txt](https://github.com/jrfonseca/xdot.py/files/12294234/factor-13.xdot.txt)

**Comment by jrfonseca** [comment] 2023-09-09 16:29
Spent a bit of time looking into this.  It seems to have some to do with escaping.

Good xdot:
```
		_ldraw_="F 14 5 -Arial c 7 -#000000 T 18.5 392.8 -1 270 40 -\e f -> Alignment:rs07_branch_HMM <8076> F 14 5 -Arial c 7 -#000000 T 8 377.8 \
-1 291 45 -(Num:multiply_double <6559> (IntMap:subscript F 14 5 -Arial c 7 -#000000 T 91 362.8 -1 125 19 -e f)) <9687> <9686> ",
		height=0.73611,
````

Bad (your) xdot:
```
		_ldraw_="F 14 5 -Arial c 7 -#000000 T 18.5 404.2 -1 269.25 40 -\\e f -> Alignment:rs07_branch_HMM <8076> F 14 5 -Arial c 7 -#000000 T 8 388.45 \
-1 290.25 45 -(Num:multiply_double <6559> (IntMap:subscript F 14 5 -Arial c 7 -#000000 T 90.88 372.7 -1 124.5 19 -e f)) <9687> <\
9686> ",

```

The issue is the `\\e`.

This seems to be related to https://github.com/jrfonseca/xdot.py/issues/92

This seems to help here,
```diff
diff --git a/xdot/ui/_xdotparser.py b/xdot/ui/_xdotparser.py
index c94c8a6..98eee4f 100644
--- a/xdot/ui/_xdotparser.py
+++ b/xdot/ui/_xdotparser.py
@@ -39,7 +40,7 @@ class XDotAttrParser:
         # `\` should be escaped as `\\`, but older versions of graphviz xdot
         # output failed to properly escape it.  See also
         # https://github.com/jrfonseca/xdot.py/issues/92
-        if not broken_backslashes:
+        if True: #not broken_backslashes:
             buf = re.sub(br'\\(.)', br'\1', buf)
 
         self.parser = parser
````

Can you check this issue happens with latest xdot from master?

**Comment by bredelings** [comment] 2023-09-09 18:47
Yes!  With that change it works.

**Comment by bredelings** [comment] 2023-09-09 18:56
Um, actually the development version works even without that change.  Apparently Debian is still shipping version 1.2 of xdot from Nov 2020.

I can file a bug on the Debian xdot package.

**Comment by jrfonseca** [comment] 2023-09-10 10:23
It looks like this is a duplicate of https://github.com/jrfonseca/xdot.py/issues/120 .

Version 1.3 was released yesterday.  It's my fault -- I should've made a release with fix earlier.

And the solution is indeed to upgrade.  Thanks

**Closed by jrfonseca** 2023-09-10 10:23 UTC
Labels: bug
