### ISSUE TITLE
Parsing error (unexpected char)

### ISSUE THREAD

**Issue by fthiery** [jrfonseca/xdot.py#49] opened 2017-12-22 15:59 UTC
I created a dot file using gstreamer. 

Xdot will crash trying to open it, but not graphviz's dot:
`$ dot -Tpng 0.00.02.363840177-gst-launch.PAUSED_READY.dot -o test.png`

```
$ xdot 0.00.02.363840177-gst-launch.PAUSED_READY.dot
/usr/lib/python3.6/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python3.6/site-packages/xdot.py:39: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1601, in set_dotcode
    self.set_xdotcode(xdotcode)
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1616, in set_xdotcode
    self.graph = parser.parse()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1285, in parse
    DotParser.parse(self)
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1082, in parse
    self.parse_graph()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1091, in parse_graph
    self.parse_stmt()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1121, in parse_stmt
    self.parse_subgraph()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1104, in parse_subgraph
    self.parse_stmt()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1121, in parse_stmt
    self.parse_subgraph()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1104, in parse_subgraph
    self.parse_stmt()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1111, in parse_stmt
    attrs = self.parse_attrs()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1146, in parse_attrs
    name, value = self.parse_attr()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1155, in parse_attr
    name = self.parse_id()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1182, in parse_id
    self.consume()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 963, in consume
    self.lookahead = next(self.lexer)
  File "/usr/lib/python3.6/site-packages/xdot.py", line 913, in __next__
    raise ParseError(msg, self.filename, line, col)
xdot.ParseError: 670:133:unexpected char b'\\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xdot", line 11, in <module>
    load_entry_point('xdot==0.7', 'gui_scripts', 'xdot')()
  File "/usr/lib/python3.6/site-packages/xdot.py", line 2159, in main
    win.open_file(args[0])
  File "/usr/lib/python3.6/site-packages/xdot.py", line 2070, in open_file
    self.set_dotcode(fp.read(), filename)
  File "/usr/lib/python3.6/site-packages/xdot.py", line 2052, in set_dotcode
    if self.dotwidget.set_dotcode(dotcode, filename):
  File "/usr/lib/python3.6/site-packages/xdot.py", line 1603, in set_dotcode
    self.error_dialog(str(ex))
AttributeError: 'DotWidget' object has no attribute 'error_dialog'
```

Here is an example dot file (zipped).

[0.00.02.363840177-gst-launch.PAUSED_READY.zip](https://github.com/jrfonseca/xdot.py/files/1582938/0.00.02.363840177-gst-launch.PAUSED_READY.zip)

I am using Arch linux's 0.7-3 xdot community package with python 3.6.3

**Comment by jrfonseca** [comment] 2017-12-22 18:45
This is a duplicate of https://github.com/jrfonseca/xdot.py/issues/19 and https://gitlab.com/graphviz/graphviz/issues/165

Dot can parse the dot file you provided.  But it can't parse the xdot it generates itself:

    $ dot -Txdot -o0.00.02.363840177-gst-launch.PAUSED_READY.xdot 0.00.02.363840177-gst-launch.PAUSED_READY.dot
    $ dot 0.00.02.363840177-gst-launch.PAUSED_READY.xdot 
Error: 0.00.02.363840177-gst-launch.PAUSED_READY.xdot: syntax error in line 670 near '\'

I'm afraid there's nothing I can do..

**Comment by j1elo** [comment] 2018-04-18 17:43
I think this issue shouldn't be closed. *xdot* needs to be able to handle valid DOT files, its own purpose and main goal is explicitly that one. If the main supporting library has a bug that prevents the expected correct behavior, this could (should?) be considered a bug in xdot itself (regardless where is the responsibility of the fix).

At a minimum, keeping this issue opened as a way of tracking progress on the fix would be a good practice; some noise in the Dot project bugtracker would also be helpful. All it was needed so far was a "me too" message in [their bug report](https://gitlab.com/graphviz/graphviz/issues/165) and it got noticed pretty quickly by the devs.

For a workaround to this issue, I've been using this simple *sed* command that cleans up the GStreamer DOT files:

```
sed -i -e 's/\\\\//g' pipeline.dot
```

**Comment by jrfonseca** [comment] 2018-04-18 20:57
Fair enough.  I don't mind keep this open for tracking/documentation.

**Comment by jrfonseca** [comment] 2018-04-18 21:14
On second thought, better to keep the original bug open.

**Closed by jrfonseca** 2018-04-18 21:14 UTC
Labels: thirdparty

**Comment by fthiery** [comment] 2018-04-19 07:48
@j1elo your workaround seems to break valid dotfiles, and doesn't always work

My much uglier workaround is to convert to svg (which does not crash), and open it with e.g. eog (eye of gnome); the problem is that svg is very resource intensive for displaying large pipelines.

```
        os.system("dot /tmp/p.dot -Tsvg -o /tmp/p.svg")
        os.system("eog /tmp/p.svg")
```
